import { DeviceItem } from '@/types/device';

export const passiveDeviceData: DeviceItem[] = [
  // ─────────────────────────────────────────────
  // 1. Pyezo Buzzer (Signalizator)
  // ─────────────────────────────────────────────
  {
    id: 'passive-001',
    slug: 'piezo-buzzer',
    type: 'audio',
    category: 'Passiv komponentlar',
    name: {
      uz: 'Pyezo Buzzer (Akustik Signalizator)',
      ru: 'Пьезоизлучатель (Зуммер)',
      en: 'Piezo Buzzer (Buzzer Module)',
    },
    shortDesc: {
      uz: "Turli chastotalarda ovoz signallari va musiqiy ohanglarni chiqaruvchi pyezo element.",
      ru: 'Акустический излучатель для подачи звуковых сигналов и воспроизведения мелодий.',
      en: 'Acoustic buzzer component for generating audible alert beeps and tones.',
    },
    overview: {
      uz: "Pyezo buzzer — ichidagi pyezoelektrik kristallga berilgan elektr signallari tebranishi natijasida tovush to'lqinlarini hosil qiladi. Passiv buzzer `tone()` funksiyasi orqali har xil notalarni chalishi mumkin.",
      ru: 'Пьезозуммер преобразует электрические колебания в звуковые волны. С помощью функции tone() может воспроизводить звуки разной высоты.',
      en: 'Converts electrical frequencies into sound waves. Controlled via tone() to play custom frequencies and melodies.',
    },
    howItWorks: {
      uz: "Arduino PWM yoki raqamli pini orqali beriladigan chastota (Hz) havodagi pyezo membranani tebratadi va bizga tovush sifatida eshitiladi.",
      ru: 'Импульсы заданной частоты с пина Arduino раскачивают мембрану пьезоэлемента.',
      en: 'Frequencies generated by Arduino pins vibrate the internal piezo membrane.',
    },
    useCases: {
      uz: "Signalizatsiyalar | Tugma bosilish tovushi | Taymer va budilniklar | Musiqiy o'yinchoqlar",
      ru: 'Охранные сигнализации | Звук нажатия кнопок | Будильники | Игрушки',
      en: 'Alarm systems | Keypress feedback | Timers & clocks | Audio cues',
    },
    voltage: '3.3V – 5V DC',
    current: '20 mA',
    imageUrl: 'https://components101.com/sites/default/files/component_pin/Buzzer-Pinout.jpg',
    specs: [
      { label: 'Turi', value: 'Passiv / Aktiv pyezo' },
      { label: 'Ishchi kuchlanish', value: '3.3V - 5V DC' },
      { label: 'Rezonans chastotasi', value: '2 - 4 kHz' },
    ],
    pinout: [
      { pin: '+ (Musbat)', name: 'VCC / Signal', type: 'Digital', description: 'Arduino PWM piniga (D8)' },
      { pin: '- (Manfiy)', name: 'GND', type: 'GND', description: 'Umumiy yerga ulanadi' },
    ],
    wiring: {
      title: { uz: 'Arduino Uno ga ulash', ru: 'Подключение к Arduino Uno', en: 'Wiring to Arduino Uno' },
      description: {
        uz: 'Musbat oyoqchani Arduino D8 ga, manfiy oyoqchani GND ga ulang.',
        ru: 'Подключите плюс к выводу D8, минус к GND.',
        en: 'Connect positive lead to D8, negative to GND.',
      },
      connections: [
        { from: 'Buzzer (+)', to: 'Arduino D8', note: 'Signal pini' },
        { from: 'Buzzer (-)', to: 'Arduino GND', note: 'Yer pini' },
      ],
    },
    sampleCode: {
      title: { uz: 'Signal chalish kodi', ru: 'Код подачи звукового сигнала', en: 'Tone beep code' },
      code: `const int buzzerPin = 8;

void setup() {
  pinMode(buzzerPin, OUTPUT);
}

void loop() {
  tone(buzzerPin, 1000); // 1000 Hz chastota
  delay(500);
  noTone(buzzerPin);
  delay(500);
}`,
    },
    troubleshooting: [
      {
        issue: 'Ovoz juda past yoki eshitilmayapti',
        cause: 'Buzzer qutblari teskari ulangan yoki chastota berilmagan.',
        solution: 'Musbat va manfiy oyoqchalarni tekshiring, tone() funksiyasini ishlating.',
      },
    ],
    tags: ['buzzer', 'audio', 'piezo', 'tone'],
  },

  // ─────────────────────────────────────────────
  // 2. 10k Potentsiometr
  // ─────────────────────────────────────────────
  {
    id: 'passive-002',
    slug: 'potentiometer-10k',
    type: 'control',
    category: 'Passiv komponentlar',
    name: {
      uz: '10k Om Aylanma Potensiometr',
      ru: 'Переменный резистор (Потенциометр) 10кОм',
      en: '10k Ohm Rotary Potentiometer',
    },
    shortDesc: {
      uz: "Burish orqali kuchlanishni 0 dan 5V gacha silliq o'zgartiruvchi analog boshqaruv dastagi.",
      ru: 'Переменный резистор для плавной регулировки аналогового напряжения от 0 до 5В.',
      en: 'Variable rotary resistor for smoothly dividing voltage from 0 to 5V.',
    },
    overview: {
      uz: "10k potentsiometr — kuchlanish bo'luvchi (voltage divider) sxemasi bo'yicha ishlaydi. Uning 3 ta oyog'i bo'lib, o'rta oyog'i burilish burchagiga mos ravishda 0 dan 5V gacha o'zgaruvchan kuchlanish chiqaradi. Arduino analog pini (A0) orqali 0-1023 oraliqdagi qiymatga o'giriladi.",
      ru: 'Потенциометр 10кОм служит делителем напряжения. Средний вывод выдает напряжение от 0 до 5В пропорционально углу поворота.',
      en: 'Acts as an adjustable voltage divider. The wiper pin outputs 0-5V read by Arduino ADC as 0-1023.',
    },
    howItWorks: {
      uz: "Dastak burilganda ichki rezistiv yo'lka bo'ylab kontakt suriladi va qarshilik o'zgaradi.",
      ru: 'При вращении ползунок перемещается по резистивному слою, меняя выходное напряжение.',
      en: 'Rotating the knob moves the wiper along a carbon track, altering resistance.',
    },
    useCases: {
      uz: "Ovoz balandligini sozlash | Chiroq yorug'ligini (Dimmer) boshqarish | Servo burchagini burash",
      ru: 'Регулировка громкости | Диммирование яркости | Управление углом сервопривода',
      en: 'Volume knob | LED dimming | Manual servo control',
    },
    voltage: '0 – 5V DC',
    imageUrl: 'https://components101.com/sites/default/files/component_pin/Potentiometer-Pinout.jpg',
    specs: [
      { label: 'Qarshilik', value: '10 kOm (10,000 Om)' },
      { label: 'Turi', value: 'Chiziqli (Linear)' },
      { label: 'Burilish burchagi', value: '300 daraja' },
    ],
    pinout: [
      { pin: '1 (Chap)', name: '5V', type: 'VCC', description: '5V kuchlanish beriladi' },
      { pin: '2 (O\'rta)', name: 'Signal (Wiper)', type: 'Analog', description: 'Arduino A0 ga ulanadi' },
      { pin: '3 (O\'ng)', name: 'GND', type: 'GND', description: 'Yerga (GND) ulanadi' },
    ],
    wiring: {
      title: { uz: 'Arduino A0 ga ulash', ru: 'Подключение к Arduino A0', en: 'Wiring to Arduino A0' },
      description: {
        uz: 'Chetki oyoqlar 5V va GND ga, o\'rtadagi oyoq Arduino A0 ga ulanadi.',
        ru: 'Крайние выводы к 5В и GND, средний к A0.',
        en: 'Outer pins to 5V and GND, wiper to A0.',
      },
      connections: [
        { from: 'Pot 1', to: 'Arduino 5V' },
        { from: 'Pot 2 (O\'rta)', to: 'Arduino A0' },
        { from: 'Pot 3', to: 'Arduino GND' },
      ],
    },
    sampleCode: {
      title: { uz: 'Analog qiymatni o\'qish', ru: 'Чтение аналогового значения', en: 'Read analog value' },
      code: `void setup() {
  Serial.begin(9600);
}

void loop() {
  int val = analogRead(A0);
  Serial.println(val);
  delay(100);
}`,
    },
    troubleshooting: [],
    tags: ['potentiometer', 'resistor', 'analog', 'control'],
  },
];
